language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
matrix:
  exclude:
    - python: "3.2"
      env: REQUIREMENTS=lowest
    - python: "3.3"
      env: REQUIREMENTS=lowest
    - python: "3.4"
      env: REQUIREMENTS=lowest
    - python: "pypy3"
      env: REQUIREMENTS=lowest
  include:
    - python: "2.7"
      env:
        - JYTHON=true
        - REQUIREMENTS=lowest
    - python: "2.7"
      env:
        - JYTHON=true
        - REQUIREMENTS=release

before_install:
  # Setting up Jython
  - chmod +x ./.scripts/jython_env.sh
  - ./.scripts/jython_env.sh
install:
  - pip install tox
script:
  - echo 'Python interpreter is '  $PYTHON_EXE
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$REQUIREMENTS