language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
matrix:
  include:
    - python: "2.7"
      env: DOCS=true
  exclude:
    - python: "3.2"
      env: REQUIREMENTS=lowest
    - python: "3.3"
      env: REQUIREMENTS=lowest
    - python: "3.4"
      env: REQUIREMENTS=lowest
    - python: "pypy3"
      env: REQUIREMENTS=lowest

install:
  - pip install tox
script:
  - if [ -z "$DOCS" ]; then tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$REQUIREMENTS; fi
  - if [ ! -z "$DOCS" ]; then tox -e docs; fi