language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
before_install:
  # Setting up Jython
  - chmod +x ./.scripts/jython_env.sh
  - ./.scripts/jython_env.sh
install:
  - pip install tox
script:
  - tox